# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CPY: './copydir'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%i-%s')"
    - name: go for the name
      run: echo "release-${{ steps.date.outputs.date }}"
    #- uses: actions/checkout@v2
    #- name: get the orig
    - name: get orig
      uses: actions/checkout@v2
      with :
        repository: geogebra/geogebra
        ref: master
        path: ${{env.CPY}}
      # all operations with gradle must bear this.
      #- name: Setup tmate sessions
      
  #  - name: wait and see
  #    uses: mxschmitt/action-tmate@v3   
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x ${{env.CPY}}/gradlew
    - name: Build with Gradle zip
#        sed -i 's/org.wisepersist.gradle.plugins.gwt.Style.DETAILED/org.wisepersist.gradle.plugins.gwt.Style.PRETTY/' ./web/build.gradle
#        cat ./web/build.gradle
# -Pgdetailed=false
      run: |
        cd ${{env.CPY}} 
        ./gradlew  :web:createSolverHtml :web:deployIntoWar :web:prepareS3Upload :web:mergeDeploy  -Pgdraft=true 
    - name: List all created files
      run: ls -Ral   
    - name: cp   
      run: |
        mkdir zip-bundle
        mkdir zip-bundle/GeoGebra
        mkdir zip-bundle/GeoGebra/HTML5
        mkdir zip-bundle/GeoGebra/HTML5/5.0
        cp -r ${{env.CPY}}/web/war/web3d zip-bundle/GeoGebra/HTML5/5.0
        cp -r ${{env.CPY}}/web/war/webSimple zip-bundle/GeoGebra/HTML5/5.0
        cp -r ${{env.CPY}}/web/war/web zip-bundle/GeoGebra/HTML5/5.0
        cp ${{env.CPY}}/web/war/deployggb.js  zip-bundle/GeoGebra
        cp ${{env.CPY}}/web/war/*.*  zip-bundle/GeoGebra/HTML5/5.0
 #   - name: Setup tmate sessions
 #     uses: mxschmitt/action-tmate@v3   
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: prettified-ggb-bundle
#??? :web:createDraftBundleZip        path: "./web/war/geogebra-large-bundle.zip"
        path: "./zip-bundle"
    - name: relase
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "bundle"
          automatic_release_tag: "latest"
          files: |
            ./zip-bundle/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "./zip-bundle/*"
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
    - name: other release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./zip-bundle/*"
        tag: "release-${{ steps.date.outputs.date }}"
        token: ${{ secrets.GITHUB_TOKEN }}
