# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle prepare S3
#      run: ./gradlew :web:prepareS3Upload -Pgdraft=true
#    - name: What hell this went to s3
#      run: ls -Ral
#   - name: Build with Gradle merge deploy
#      run: ./gradlew :web:mergeDeploy    -Pgdraft=true 
#    - name: What hell this went to merge
#      run: ls -Ral
#    - name: Build with Gradle war
#      run: ./gradlew :web:deploIntoWar -Pgdraft=true
#    - name: What hell this went to war
#      run: ls -Ral
    - name: Build with Gradle zip
      run: ./gradlew  :web:createDraftBundleZip  -Pgdraft=true 
    - name: What hell this went to zip
      run: ls -Ral      
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp1
#??? :web:createDraftBundleZip        path: "./web/war/geogebra-bundle.zip"
        path: "./web/war/geogebra-bundle.zip"
      
